#!/bin/sh

pgbouncer_initialize()
{
  typeset postgresql_version

  # TODO: detect the version installed in SM...?
  postgresql_version="$(psql -V | head -1 | awk '{print $NF}')"

  package_version=$(pgbouncer_versions_latest)
  package_url=$(pgbouncer_version_url "${package_version}")
  package_file="${package_url##*/}"
  package_dir="${package_file%.*}"
}

pgbouncer_versions()
{
  typeset -ga versions
  versions=($(
    curl -s "http://pgfoundry.org/frs/?group_id=1000258" |
      grep '/frs/download.php' |
      sed -e 's/.*download.php\///' -e 's/">.*$//' |
      sort -r
  ))
}

pgbouncer_latest()
{
  pgbouncer_versions
  typeset -g latest
  latest=${versions[1]}
}

pgbouncer_versions_latest(){
  pgbouncer_latest

  latest="${latest%.tgz}"
  latest="${latest#*-}"
  log "${latest}"
}

pgbouncer_versions_available() {
  pgbouncer_versions

  for version in ${versions[@]}
  do
    version="${version%.tgz}"
    version="${version#*-}"
    log "${version}"
  done
}

pgbouncer_version_url()
{
  typeset _version _path _current

  _version="$1" && shift || fail "A version number must be given."

  pgbouncer_versions

  for _path in ${versions[@]}
  do
    _current="${_path%.tgz}"
    _current="${version#*-}"

    if [[ "${version}" == "${_current}" ]]
    then
      log "http://pgfoundry.org/frs/download.php/${_path}"
      break
    fi
  done
}
