#!/bin/sh

typeset -x timestamp master_file sync_file replicas_file replicating_file my_role \
  pgha_log pgha_path sync_ip master_ip firstReplica PGDATA DEBUG etcd_addr \
  expected_master expected_sync current_master current_sync pgha_conf

declare -ax replica_ips my_ips args asyncdirs expected_async current_async async_ips \
  tags

export PATH="/bin:/usr/bin:/sbin:/usr/sbin:/opt/sm/pkg/active/bin:/usr/local/bin"
(( ${DEBUG:=0} == 0 )) || set -x

pgha_conf=/etc/pgha/pgha.conf

read_config_defaults

read_config

require_variables PGDATA

parse_args

pgha_path=${PGDATA}/../pgha
pgha_log=${pgha_path}/pgha.log
master_file=${pgha_path}/master
sync_file=${pgha_path}/sync
replicas_file=${pgha_path}/replicas
replicating_file=${pgha_path}/replicating

timestamp=$(date +"%Y-%m-%dT%H:%M:%S")

my_ips=($(ip addr list | awk '/inet / && /eth*/ &&!/127.0.0.1/{print $2}' | sed -e 's|/.*$||'))

read_pgha_ips

