#!/bin/sh

typeset -x timestamp masterFile syncFile replicasFile replicatingFile myRole 
typeset -x pghaPath syncIP masterIP firstReplica PGDATA DEBUG pghaLog etcd_ip
declare -ax replicaIPs myIPs args

typeset -x expected_master expected_sync current_master current_sync
declare -ax asyncdirs expected_async current_async

export PATH="/bin:/usr/bin:/sbin:/usr/sbin:/opt/sm/pkg/active/bin:/usr/local/bin"
(( ${DEBUG:=0} == 0 )) || set -x

require_postgres_user

read_config_defaults

require_pgdata

parse_args

pghaPath=${PGDATA}/../pgha
pghaLog=${pghaPath}/pgha.log
masterFile=${pghaPath}/master
syncFile=${pghaPath}/sync
replicasFile=${pghaPath}/replicas
replicatingFile=${pghaPath}/replicating

timestamp=$(date +"%Y-%m-%dT%H:%M:%S")

myIPs=($(ip addr list | awk '/inet / && /eth*/ &&!/127.0.0.1/{print $2}' | sed -e 's|/.*$||'))

read_pgha_ips

