#!/bin/sh

must_not_be_root() {
	if (( UID == 0 ))
	then
		echo "$0 cannot be run as root, must be run as 'postgres' user."
		exit 1
	fi
}

must_be_root() {
	if (( UID > 0 ))
	then
		echo "$0 must be run as root."
		exit 1
	fi
}

detect_os() {
	osRelease=$(cat /etc/*release* | tr '\n' ' ')
	case "${osRelease}" in
		(*CentOS*)
			os="centos"
			pkg="yum"
			;;
		(*edora*)
			os="fedora"
			pkg="yum"
			;;
		(*buntu*)
			os="ubuntu"
			pkg="apt-get"
			;;
		(*ebian*)
			os="debian"
			pkg="apt-get"
			;;
		(*)
			echo "ERROR: Unhandled Operating System Release ${osRelease}"
			exit 1
			;;
	esac
}

setup_os_packages() {
	detect_os

  echo "=> Setup OS Packages"
  case ${pkg} in 
    (yum)
      yum install -y python-virtualenv libevent-dev pv lzop python-pip
			;;
    (apt-get)
      apt-get install -y python-virtualenv libevent-dev pv lzop python-pip
			;;
  esac
}

install_wal_e() {
	pip install git+https://github.com/wal-e/wal-e
}

