#!/bin/sh

typeset -g json_file file service_user service_data_path master replica port \
  password user identity ssh_port ssh_identity ssh_options
typeset -ga _initdb_flags configure_flags >/dev/null 2>&1 # Don't care if declared already.
typeset -gx PGDATA

if file exists "/etc/system.json"
then
  json_file="/etc/system.json"
else
  json_file="${extension_path}/config/defaults.json"
fi

postgresql_defaults

