#!/bin/sh

rubyrep_initialize()
{
  build_command="true"
  install_command="true"
}

rubyrep_configure()
{
  if ! file is executable "/usr/local/rvm/wrappers/jruby-1.6.5/ruby"
  then sm rubyrep jruby install ; fi
}

rubyrep_install()
{
  /usr/local/rvm/wrappers/jruby-1.6.5/ruby -S /opt/sm/src/rubyrep-1.2.0/setup.rb # --prefix=/opt/sm/pkg/versions/rubyrep/1.2.0


  "/usr/local/rvm/wrappers/jruby-1.6.5/ruby" -S \
    "${sm_path}/src/rubyrep-${package_version}/setup.rb" > install.log 2>&1
    # --prefix "${sm_path}/pkg/versions/rubyrep/${package_version}"

  package activate name "rubyrep" version ${package_version}
}
