#!/bin/sh

rubyrep_initialize()
{
  trace_filter rubyrep || set +o xtrace

  build_command="true"
  install_command="true"
}

rubyrep_configure()
{
  true
}

rubyrep_install()
{
  trace_filter rubyrep || set +o xtrace

  ./jruby/bin/jruby setup.rb all --prefix=/opt/sm/pkg/versions/rubyrep/1.2.0 > install.log 2>&1

  package activate name "rubyrep" version ${package_version}
}
